//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="WCF_Service_1000", ConfigurationName="IBirthday")]
public interface IBirthday
{
    
    [System.ServiceModel.OperationContractAttribute(Action="WCF_Service_1000/IBirthday/To1000", ReplyAction="WCF_Service_1000/IBirthday/To1000Response")]
    double To1000(int year, int month, int day);
    
    [System.ServiceModel.OperationContractAttribute(Action="WCF_Service_1000/IBirthday/To1000", ReplyAction="WCF_Service_1000/IBirthday/To1000Response")]
    System.Threading.Tasks.Task<double> To1000Async(int year, int month, int day);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IBirthdayChannel : IBirthday, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class BirthdayClient : System.ServiceModel.ClientBase<IBirthday>, IBirthday
{
    
    public BirthdayClient()
    {
    }
    
    public BirthdayClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public BirthdayClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BirthdayClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BirthdayClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public double To1000(int year, int month, int day)
    {
        return base.Channel.To1000(year, month, day);
    }
    
    public System.Threading.Tasks.Task<double> To1000Async(int year, int month, int day)
    {
        return base.Channel.To1000Async(year, month, day);
    }
}
