//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="WCF_Service_Day", ConfigurationName="IDays")]
public interface IDays
{
    
    [System.ServiceModel.OperationContractAttribute(Action="WCF_Service_Day/IDays/Day", ReplyAction="WCF_Service_Day/IDays/DayResponse")]
    double Day(int year, int month, [System.ServiceModel.MessageParameterAttribute(Name="day")] int day1);
    
    [System.ServiceModel.OperationContractAttribute(Action="WCF_Service_Day/IDays/Day", ReplyAction="WCF_Service_Day/IDays/DayResponse")]
    System.Threading.Tasks.Task<double> DayAsync(int year, int month, int day);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IDaysChannel : IDays, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DaysClient : System.ServiceModel.ClientBase<IDays>, IDays
{
    
    public DaysClient()
    {
    }
    
    public DaysClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DaysClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DaysClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DaysClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public double Day(int year, int month, int day1)
    {
        return base.Channel.Day(year, month, day1);
    }
    
    public System.Threading.Tasks.Task<double> DayAsync(int year, int month, int day)
    {
        return base.Channel.DayAsync(year, month, day);
    }
}
