//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="WSF_Service_Hobby", ConfigurationName="IHobby")]
public interface IHobby
{
    
    [System.ServiceModel.OperationContractAttribute(Action="WSF_Service_Hobby/IHobby/MovieFromYear", ReplyAction="WSF_Service_Hobby/IHobby/MovieFromYearResponse")]
    string MovieFromYear(string textBox);
    
    [System.ServiceModel.OperationContractAttribute(Action="WSF_Service_Hobby/IHobby/MovieFromYear", ReplyAction="WSF_Service_Hobby/IHobby/MovieFromYearResponse")]
    System.Threading.Tasks.Task<string> MovieFromYearAsync(string textBox);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IHobbyChannel : IHobby, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class HobbyClient : System.ServiceModel.ClientBase<IHobby>, IHobby
{
    
    public HobbyClient()
    {
    }
    
    public HobbyClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public HobbyClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HobbyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HobbyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string MovieFromYear(string textBox)
    {
        return base.Channel.MovieFromYear(textBox);
    }
    
    public System.Threading.Tasks.Task<string> MovieFromYearAsync(string textBox)
    {
        return base.Channel.MovieFromYearAsync(textBox);
    }
}
